export * from './user';
export * from './clinic';
export * from './territory';
export * from './settings/marketing-items';
export * from './settings/pathologies';
export * from './settings/surgery';
export * from './patient';
export * from './patient-session/patient-session';
export * from './patient-session/qr-linker';
export * from './questionnaire';
export * from './equipment';
export * from './outcome';
export * from './languages';
export * from './appointment';
export * from './treatment';
export * from './dblogger';
export * from './gait';
export * from './reports';

